(() => {
  'use strict';

  const SIZE = 45;
  const CELL = 16;
  const ART_SIZE = SIZE * CELL;
  const MIN_ZOOM = .2;
  const MAX_ZOOM = 8;
  const MIN_DELTA_E = 8;
  const DEFAULT_MIN_DELTA_E = 12;
  const DEFAULT_COLOR = '#777777';
  const STORAGE_KEY = 'pixelAtelier:state:v2';
  const APP_VERSION = '2.1.0';
  const DEFAULT_COLORS = [];

  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
  const clone = value => JSON.parse(JSON.stringify(value));
  const uid = () => `c${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`;
  const bootStarted = performance.now();
  const bootEntries = [];
  function bootLog(stage,details={}){const entry={stage,ms:Math.round(performance.now()-bootStarted),details};bootEntries.push(entry);window.__PIXEL_ATELIER_DEBUG__={status:stage,bootEntries:[...bootEntries]};const detailText=Object.keys(details).length?` ${JSON.stringify(details)}`:'';console.info(`[Pixel Atelier +${entry.ms}ms] ${stage}${detailText}`)}

  function hexToRgb(hex) {
    const clean = hex.replace('#', '').trim();
    if (!/^[0-9a-f]{6}$/i.test(clean)) return null;
    const n = parseInt(clean, 16);
    return {r: n >> 16, g: (n >> 8) & 255, b: n & 255};
  }
  function rgbToHex(r, g, b) {
    return '#' + [r,g,b].map(v => clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('');
  }
  function rgbToXyz({r,g,b}) {
    const linear = v => { v /= 255; return v > .04045 ? ((v + .055) / 1.055) ** 2.4 : v / 12.92; };
    r = linear(r); g = linear(g); b = linear(b);
    return {x:(r*.4124+g*.3576+b*.1805)*100,y:(r*.2126+g*.7152+b*.0722)*100,z:(r*.0193+g*.1192+b*.9505)*100};
  }
  function xyzToLab({x,y,z}) {
    x/=95.047; y/=100; z/=108.883;
    const f = v => v > .008856 ? Math.cbrt(v) : 7.787*v + 16/116;
    const fx=f(x), fy=f(y), fz=f(z);
    return {L:116*fy-16,a:500*(fx-fy),b:200*(fy-fz)};
  }
  const rgbToLab = rgb => xyzToLab(rgbToXyz(rgb));
  function labToRgb({L,a,b}) {
    let y=(L+16)/116, x=a/500+y, z=y-b/200;
    const inv = v => v**3 > .008856 ? v**3 : (v-16/116)/7.787;
    x=95.047*inv(x)/100; y=100*inv(y)/100; z=108.883*inv(z)/100;
    let r=x*3.2406+y*-1.5372+z*-.4986, g=x*-.9689+y*1.8758+z*.0415, bl=x*.0557+y*-.204+z*1.057;
    const gamma = v => 255*(v > .0031308 ? 1.055*v**(1/2.4)-.055 : 12.92*v);
    return {r:clamp(gamma(r),0,255),g:clamp(gamma(g),0,255),b:clamp(gamma(bl),0,255)};
  }
  function rgbToHsl({r,g,b}) {
    r/=255;g/=255;b/=255; const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min; let h=0;
    if(d){ if(max===r)h=((g-b)/d)%6; else if(max===g)h=(b-r)/d+2; else h=(r-g)/d+4; h*=60;if(h<0)h+=360; }
    const l=(max+min)/2, s=d===0?0:d/(1-Math.abs(2*l-1)); return {h,s:s*100,l:l*100};
  }
  function hslToRgb({h,s,l}) {
    h=((h%360)+360)%360;s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;
    if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}
    return {r:(r+m)*255,g:(g+m)*255,b:(b+m)*255};
  }
  function deltaE00(lab1, lab2) {
    const {L:L1,a:a1,b:b1}=lab1,{L:L2,a:a2,b:b2}=lab2;
    const C1=Math.hypot(a1,b1),C2=Math.hypot(a2,b2),Cbar=(C1+C2)/2;
    const G=.5*(1-Math.sqrt(Cbar**7/(Cbar**7+25**7)));
    const ap1=(1+G)*a1,ap2=(1+G)*a2,cp1=Math.hypot(ap1,b1),cp2=Math.hypot(ap2,b2);
    const hp=(a,b)=>{let h=Math.atan2(b,a)*180/Math.PI;return h<0?h+360:h};
    const hp1=hp(ap1,b1),hp2=hp(ap2,b2),dLp=L2-L1,dCp=cp2-cp1;let dhp=hp2-hp1;
    if(cp1*cp2===0)dhp=0;else if(dhp>180)dhp-=360;else if(dhp<-180)dhp+=360;
    const dHp=2*Math.sqrt(cp1*cp2)*Math.sin(dhp*Math.PI/360),Lp=(L1+L2)/2,Cp=(cp1+cp2)/2;let hpbar;
    if(cp1*cp2===0)hpbar=hp1+hp2;else if(Math.abs(hp1-hp2)<=180)hpbar=(hp1+hp2)/2;else hpbar=(hp1+hp2+360)/2%360;
    const T=1-.17*Math.cos((hpbar-30)*Math.PI/180)+.24*Math.cos(2*hpbar*Math.PI/180)+.32*Math.cos((3*hpbar+6)*Math.PI/180)-.20*Math.cos((4*hpbar-63)*Math.PI/180);
    const dTheta=30*Math.exp(-(((hpbar-275)/25)**2)),Rc=2*Math.sqrt(Cp**7/(Cp**7+25**7)),Sl=1+.015*(Lp-50)**2/Math.sqrt(20+(Lp-50)**2),Sc=1+.045*Cp,Sh=1+.015*Cp*T,Rt=-Math.sin(2*dTheta*Math.PI/180)*Rc;
    return Math.sqrt((dLp/Sl)**2+(dCp/Sc)**2+(dHp/Sh)**2+Rt*(dCp/Sc)*(dHp/Sh));
  }
  const colorLab = hex => rgbToLab(hexToRgb(hex));
  const contrastText = hex => {const c=hexToRgb(hex);return c.r*.299+c.g*.587+c.b*.114>155?'#111':'#fff'};
  const SVG_NS='http://www.w3.org/2000/svg',BASE_CACHE_LIMIT=8;
  const labBaseCache=new Map(),wheelBaseCache=new Map(),labRestrictionCache=new Map(),wheelRestrictionCache=new Map(),labRegionCache=new Map(),wheelRegionCache=new Map();
  const LAB_MODEL=(()=>{const width=210,height=150,a=new Float32Array(width*height),b=new Float32Array(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=y*width+x;a[i]=x/(width-1)*220-110;b[i]=110-y/(height-1)*220}return{width,height,a,b}})();
  const WHEEL_MODEL=(()=>{const width=180,height=180,hue=new Float32Array(width*height),saturation=new Float32Array(width*height),inside=new Uint8Array(width*height),cx=(width-1)/2,cy=(height-1)/2,radius=Math.min(width,height)/2-2;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=y*width+x,dx=x-cx,dy=y-cy,s=Math.hypot(dx,dy)/radius;if(s<=1){inside[i]=1;hue[i]=(Math.atan2(dy,dx)*180/Math.PI+360)%360;saturation[i]=s*100}}return{width,height,hue,saturation,inside}})();
  function cacheValue(cache,key,builder,limit=BASE_CACHE_LIMIT){if(cache.has(key)){const value=cache.get(key);cache.delete(key);cache.set(key,value);return value}const value=builder();cache.set(key,value);while(cache.size>limit)cache.delete(cache.keys().next().value);return value}
  function buildModelCanvas(model,pixelAt){const canvas=document.createElement('canvas');canvas.width=model.width;canvas.height=model.height;const ctx=canvas.getContext('2d'),image=ctx.createImageData(model.width,model.height);for(let i=0;i<model.width*model.height;i++){const color=pixelAt(i);if(!color)continue;const p=i*4;image.data[p]=color.r;image.data[p+1]=color.g;image.data[p+2]=color.b;image.data[p+3]=255}ctx.putImageData(image,0,0);return canvas}
  function displayPalette(){return colorDragPreview&&editingId?state.palette.map(entry=>entry.id===editingId?{...entry,color:candidate,previewLab:labCursor,previewHsl:wheelCursor}:entry):state.palette}
  function entrySignature(entry){const lab=entry.previewLab?`:${entry.previewLab.a.toFixed(2)},${entry.previewLab.b.toFixed(2)}`:'',hsl=entry.previewHsl?`:${entry.previewHsl.h.toFixed(2)},${entry.previewHsl.s.toFixed(2)}`:'';return `${entry.id}:${entry.color}${lab}${hsl}`}
  function paletteSignature(entries=displayPalette()){return entries.map(entrySignature).join('|')}
  function actualLabFromLab(lab){const rgb=labToRgb(lab);return rgbToLab({r:clamp(Math.round(rgb.r),0,255),g:clamp(Math.round(rgb.g),0,255),b:clamp(Math.round(rgb.b),0,255)})}
  function actualLabFromHsl(hsl){const rgb=hslToRgb(hsl);return rgbToLab({r:clamp(Math.round(rgb.r),0,255),g:clamp(Math.round(rgb.g),0,255),b:clamp(Math.round(rgb.b),0,255)})}
  function smoothClosedPath(points){if(points.length<3)return'';let d=`M${points[0].x.toFixed(2)} ${points[0].y.toFixed(2)}`;for(let i=0;i<points.length;i++){const p0=points[(i-1+points.length)%points.length],p1=points[i],p2=points[(i+1)%points.length],p3=points[(i+2)%points.length],c1x=p1.x+(p2.x-p0.x)/6,c1y=p1.y+(p2.y-p0.y)/6,c2x=p2.x-(p3.x-p1.x)/6,c2y=p2.y-(p3.y-p1.y)/6;d+=`C${c1x.toFixed(2)} ${c1y.toFixed(2)} ${c2x.toFixed(2)} ${c2y.toFixed(2)} ${p2.x.toFixed(2)} ${p2.y.toFixed(2)}`}return d+'Z'}
  function radialContour(cx,cy,limitAt,blockedAt,mapPoint){if(!blockedAt(cx,cy))return'';const points=[];for(let degree=0;degree<360;degree+=5){const angle=degree*Math.PI/180,dx=Math.cos(angle),dy=Math.sin(angle),limit=Math.max(0,limitAt(cx,cy,dx,dy));let low=0,high=limit;if(!blockedAt(cx+dx*high,cy+dy*high)){for(let i=0;i<10;i++){const mid=(low+high)/2;if(blockedAt(cx+dx*mid,cy+dy*mid))low=mid;else high=mid}}else low=high;points.push(mapPoint(cx+dx*low,cy+dy*low))}return smoothClosedPath(points)}
  function labRayLimit(a,b,dx,dy){const limits=[];if(dx>0)limits.push((110-a)/dx);else if(dx<0)limits.push((-110-a)/dx);if(dy>0)limits.push((110-b)/dy);else if(dy<0)limits.push((-110-b)/dy);return Math.min(...limits.filter(value=>value>=0))}
  function circleRayLimit(x,y,dx,dy){const dot=x*dx+y*dy;return Math.max(0,-dot+Math.sqrt(Math.max(0,dot*dot+1-x*x-y*y)))}
  function buildLabRestrictions(L,w,h,entries=displayPalette()){return entries.map(entry=>cacheValue(labRegionCache,`${state.minDeltaE}|${L}|${w}x${h}|${entrySignature(entry)}`,()=>{const paletteLab=colorLab(entry.color),center=entry.previewLab||paletteLab,blockedAt=(a,b)=>deltaE00(actualLabFromLab({L,a,b}),paletteLab)<state.minDeltaE,d=radialContour(center.a,center.b,labRayLimit,blockedAt,(a,b)=>({x:(a+110)/220*w,y:(110-b)/220*h}));return d?{id:entry.id,color:entry.color,d}:null},160)).filter(Boolean)}
  function buildWheelRestrictions(L,w,h,entries=displayPalette()){const radius=Math.min(w,h)/2-3,cx=w/2,cy=h/2;return entries.map(entry=>cacheValue(wheelRegionCache,`${state.minDeltaE}|${L}|${w}x${h}|${entrySignature(entry)}`,()=>{const paletteLab=colorLab(entry.color),hsl=entry.previewHsl||rgbToHsl(hexToRgb(entry.color)),angle=hsl.h*Math.PI/180,x=Math.cos(angle)*hsl.s/100,y=Math.sin(angle)*hsl.s/100,blockedAt=(px,py)=>{const saturation=Math.hypot(px,py);if(saturation>1)return false;return deltaE00(actualLabFromHsl({h:(Math.atan2(py,px)*180/Math.PI+360)%360,s:saturation*100,l:L}),paletteLab)<state.minDeltaE},d=radialContour(x,y,circleRayLimit,blockedAt,(px,py)=>({x:cx+px*radius,y:cy+py*radius}));return d?{id:entry.id,color:entry.color,d}:null},160)).filter(Boolean)}
  function renderRestrictionLayer(layer,key,regions){if(layer.dataset.key===key)return;layer.dataset.key=key;layer.replaceChildren();regions.forEach(region=>{const fill=document.createElementNS(SVG_NS,'path'),edge=document.createElementNS(SVG_NS,'path');fill.setAttribute('d',region.d);fill.setAttribute('fill',region.color);fill.classList.add('restriction-fill');edge.setAttribute('d',region.d);edge.classList.add('restriction-boundary');layer.append(fill,edge)})}
  function renderMarkerLayer(layer,key,markers){if(layer.dataset.key===key)return;layer.dataset.key=key;layer.replaceChildren();markers.forEach(marker=>{const circle=document.createElementNS(SVG_NS,'circle'),label=document.createElementNS(SVG_NS,'text');circle.setAttribute('cx',marker.x);circle.setAttribute('cy',marker.y);circle.setAttribute('r',marker.active?8:6);circle.setAttribute('fill',marker.color);circle.setAttribute('stroke',contrastText(marker.color));circle.classList.add('palette-marker');if(marker.active)circle.classList.add('active');label.setAttribute('x',marker.x);label.setAttribute('y',marker.y);label.setAttribute('fill',contrastText(marker.color));label.classList.add('palette-marker-label');label.textContent=marker.label;layer.append(circle,label)})}
  function updateCandidateMarker(marker,x,y,visible=true){marker.setAttribute('cx',x);marker.setAttribute('cy',y);marker.style.opacity=visible?'1':'0';marker.style.setProperty('--candidate-color',candidate);marker.style.setProperty('--candidate-stroke',candidateIsValid?contrastText(candidate):'#ff3b30')}

  const makeDefaultState=()=>({palette:DEFAULT_COLORS.map((color,i)=>({id:`p${i}`,color})),pixels:Array(SIZE*SIZE).fill(null),currentId:null,tool:'pen',symmetry:'none',grid:false,minDeltaE:DEFAULT_MIN_DELTA_E,penBrushShape:'square',penBrushRadius:0,eraserBrushShape:'square',eraserBrushRadius:0});
  let state = makeDefaultState();
  let selection = new Set(), clipboard = null, paste = null;
  let zoom=1, panX=0, panY=0;
  let history=[], redoHistory=[], pendingAction=null;
  let drawSession=null, lastPenEnd=null, activePanel=null, fillMode='adjacent';
  let candidate=DEFAULT_COLOR, editingId=null, colorView='lab',labCursor=null,wheelCursor=null,candidateIsValid=true,colorDragPreview=false,altEyedropper=false;
  let importState=null;

  const dom = {
    canvas:$('#canvas'), transform:$('#canvasTransform'), viewport:$('#viewport'), preview:$('#previewLayer'), selection:$('#selectionLayer'),
    pattern:$('.transparency-pattern'), cancelSelection:$('#cancelCanvasSelection'), optionDock:$('#optionDock'), historyList:$('#historyList'), colorDialog:$('#colorDialog'), importDialog:$('#importDialog')
  };

  function paletteColor(id){return state.palette.find(c=>c.id===id)?.color||null}
  function indexOf(x,y){return y*SIZE+x}
  function pixelEditable(x,y){return !selection.size||selection.has(indexOf(x,y))}
  function snapshot(){return {palette:clone(state.palette),pixels:[...state.pixels],currentId:state.currentId,tool:state.tool,symmetry:state.symmetry,grid:state.grid,minDeltaE:state.minDeltaE,penBrushShape:state.penBrushShape,penBrushRadius:state.penBrushRadius,eraserBrushShape:state.eraserBrushShape,eraserBrushRadius:state.eraserBrushRadius,selection:[...selection]}}
  function normalizeSnapshot(s){
    if(!s||!Array.isArray(s.palette)||s.palette.length>16||!Array.isArray(s.pixels)||s.pixels.length!==SIZE*SIZE)throw new Error('自动保存的数据结构不兼容');
    const ids=new Set(),palette=s.palette.map((entry,i)=>{if(!entry||typeof entry.id!=='string'||!entry.id||ids.has(entry.id)||!hexToRgb(entry.color))throw new Error(`自动保存的调色板第 ${i+1} 项无效`);ids.add(entry.id);return {id:entry.id,color:entry.color.toLowerCase()}});
    const pixels=s.pixels.map(id=>id===null||ids.has(id)?id:null),tools=['pen','eraser','eyedropper','fill','line','rect','circle','select'],symmetries=['none','horizontal','vertical','both','rotate4','rotate8'];
    const minDeltaE=Number.isFinite(+s.minDeltaE)&&+s.minDeltaE>=MIN_DELTA_E?+s.minDeltaE:DEFAULT_MIN_DELTA_E;return {palette,pixels,currentId:ids.has(s.currentId)?s.currentId:(palette[0]?.id||null),tool:tools.includes(s.tool)?s.tool:'pen',symmetry:symmetries.includes(s.symmetry)?s.symmetry:'none',grid:s.grid!==false,minDeltaE,selection:Array.isArray(s.selection)?s.selection.filter(i=>Number.isInteger(i)&&i>=0&&i<SIZE*SIZE):[]};
  }
  function applySnapshot(s){state.palette=clone(s.palette);state.pixels=[...s.pixels];state.currentId=s.currentId;state.tool=s.tool;state.symmetry=s.symmetry;state.grid=s.grid;state.minDeltaE=Number.isFinite(+s.minDeltaE)&&+s.minDeltaE>=MIN_DELTA_E?+s.minDeltaE:DEFAULT_MIN_DELTA_E;const legacyShape=['circle','square'].includes(s.brushShape)?s.brushShape:'square',legacyRadius=clamp(Math.round(+s.brushRadius||0),0,8);state.penBrushShape=['circle','square'].includes(s.penBrushShape)?s.penBrushShape:legacyShape;state.penBrushRadius=Number.isFinite(+s.penBrushRadius)?clamp(Math.round(+s.penBrushRadius),0,8):legacyRadius;state.eraserBrushShape=['circle','square'].includes(s.eraserBrushShape)?s.eraserBrushShape:legacyShape;state.eraserBrushRadius=Number.isFinite(+s.eraserBrushRadius)?clamp(Math.round(+s.eraserBrushRadius),0,8):legacyRadius;selection=new Set(s.selection||[]);paste=null;lastPenEnd=null;renderAll();syncColorEditorSelection()}
  function beginAction(label){if(!pendingAction)pendingAction={label,before:snapshot()}}
  function commitAction(){if(!pendingAction)return;const after=snapshot();if(JSON.stringify(pendingAction.before)!==JSON.stringify(after)){history.push({...pendingAction,after,time:Date.now()});if(history.length>120)history.shift();redoHistory=[]}pendingAction=null;renderHistory();saveLocal()}
  function cancelAction(){if(pendingAction){applySnapshot(pendingAction.before);pendingAction=null}}
  function undo(){const item=history.pop();if(!item)return;redoHistory.push(item);applySnapshot(item.before);renderHistory();saveLocal()}
  function redo(){const item=redoHistory.pop();if(!item)return;history.push(item);applySnapshot(item.after);renderHistory();saveLocal()}
  function renderHistory(){
    dom.historyList.innerHTML='';$('#undo').disabled=!history.length;$('#redo').disabled=!redoHistory.length;if(!history.length){dom.historyList.innerHTML='<span class="microcopy">还没有变动</span>';return}
    history.slice(-12).reverse().forEach((item,i)=>{const el=document.createElement('span');el.className='history-item'+(i===0?' current':'');el.innerHTML=`<b>${history.length-i}</b>${item.label}`;dom.historyList.append(el)});
  }
  function saveLocal(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(snapshot()));$('#saveStatus').textContent='已自动保存'}catch(error){console.warn('[Pixel Atelier] 自动保存失败',error);$('#saveStatus').textContent='保存失败'}}
  function loadLocal(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw){bootLog('storage:empty');return}const saved=JSON.parse(raw),normalized=normalizeSnapshot(saved);['brushShape','brushRadius','penBrushShape','penBrushRadius','eraserBrushShape','eraserBrushRadius'].forEach(key=>normalized[key]=saved[key]);applySnapshot(normalized);bootLog('storage:restored',{colors:state.palette.length})}catch(error){state=makeDefaultState();selection=new Set();console.warn('[Pixel Atelier] 已忽略无效的自动保存数据',error);bootLog('storage:rejected',{message:error.message})}}
  function toast(text){const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.append(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),220)},1900)}

  function buildCanvas(){
    const frag=document.createDocumentFragment();
    for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const p=document.createElement('div');p.className='pixel';p.dataset.x=x;p.dataset.y=y;
      if(x===22)p.classList.add('center-left','center-right');if(y===22)p.classList.add('center-top','center-bottom');frag.append(p)}
    dom.canvas.append(frag);
  }
  function renderCanvas(){
    const children=dom.canvas.children;
    for(let i=0;i<children.length;i++){const color=paletteColor(state.pixels[i]);children[i].style.backgroundColor=color||'transparent'}
    dom.canvas.classList.toggle('no-grid',!state.grid);$('#toggleGrid').classList.toggle('active',state.grid);
  }
  function renderSelection(){
    dom.selection.innerHTML='';dom.cancelSelection.hidden=!selection.size&&!paste;const frag=document.createDocumentFragment();
    if(paste){for(let y=0;y<paste.h;y++)for(let x=0;x<paste.w;x++){const cell=paste.cells[y][x];if(!cell?.selected)continue;const tx=paste.x+x,ty=paste.y+y;if(tx<0||ty<0||tx>=SIZE||ty>=SIZE)continue;const e=document.createElement('i');e.className='paste-pixel';e.style.left=`${tx*CELL}px`;e.style.top=`${ty*CELL}px`;e.style.backgroundColor=paletteColor(cell.id)||'transparent';frag.append(e)}const b=document.createElement('i');b.className='selection-box';b.style.cssText=`left:${paste.x*CELL}px;top:${paste.y*CELL}px;width:${paste.w*CELL}px;height:${paste.h*CELL}px`;frag.append(b)}
    else if(selection.size){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),defs=document.createElementNS(ns,'defs'),pattern=document.createElementNS(ns,'pattern'),base=document.createElementNS(ns,'rect'),stripe=document.createElementNS(ns,'path'),shape=document.createElementNS(ns,'path');svg.classList.add('selection-mask');svg.setAttribute('viewBox',`0 0 ${ART_SIZE} ${ART_SIZE}`);svg.setAttribute('aria-hidden','true');pattern.id='selectionStripePattern';pattern.setAttribute('width','6');pattern.setAttribute('height','6');pattern.setAttribute('patternUnits','userSpaceOnUse');base.setAttribute('width','6');base.setAttribute('height','6');base.setAttribute('fill','rgba(237,99,55,.16)');stripe.setAttribute('d','M-1 1L1-1M0 6L6 0M5 7L7 5');stripe.setAttribute('fill','none');stripe.setAttribute('stroke','rgba(255,255,255,.72)');stripe.setAttribute('stroke-width','.85');if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const motion=document.createElementNS(ns,'animateTransform');motion.setAttribute('attributeName','patternTransform');motion.setAttribute('type','translate');motion.setAttribute('from','0 0');motion.setAttribute('to','6 0');motion.setAttribute('dur','.55s');motion.setAttribute('repeatCount','indefinite');pattern.append(motion)}pattern.append(base,stripe);defs.append(pattern);shape.setAttribute('d',[...selection].map(i=>{const x=i%SIZE*CELL,y=Math.floor(i/SIZE)*CELL;return `M${x} ${y}h${CELL}v${CELL}h-${CELL}z`}).join(''));shape.setAttribute('fill','url(#selectionStripePattern)');svg.append(defs,shape);frag.append(svg)}
    dom.selection.append(frag);
  }
  function renderPreview(points,color=paletteColor(state.currentId)){dom.preview.innerHTML='';const frag=document.createDocumentFragment();points.forEach(({x,y})=>{if(x<0||y<0||x>=SIZE||y>=SIZE||!pixelEditable(x,y))return;const e=document.createElement('i');e.className='preview-pixel';e.style.left=`${x*CELL}px`;e.style.top=`${y*CELL}px`;e.style.backgroundColor=color||'transparent';frag.append(e)});dom.preview.append(frag)}
  let paletteDragSuppressClickUntil=0;
  function renderPalette(){
    $('#studioPaletteCount').textContent=`${state.palette.length} / 16`;$('#clearPalette').disabled=!state.palette.length;$('#paletteDeltaRule').textContent=state.minDeltaE;['minDeltaE','importMinDeltaE'].forEach(id=>{const deltaInput=$('#'+id);if(deltaInput&&document.activeElement!==deltaInput){deltaInput.value=state.minDeltaE;deltaInput.classList.remove('invalid')}});renderStudioPalette();updateStatus();
  }
  function activeBrushTool(){return state.tool==='eraser'?'eraser':'pen'}
  function brushSettings(tool=activeBrushTool()){return{shape:state[`${tool}BrushShape`]||'square',radius:clamp(Math.round(+state[`${tool}BrushRadius`]||0),0,8)}}
  function renderBrushControls(){const tool=activeBrushTool(),{shape,radius}=brushSettings(tool),input=$('#brushRadius');$$('[data-brush-shape]').forEach(button=>button.classList.toggle('active',button.dataset.brushShape===shape));input.value=radius;input.nextElementSibling.textContent=`${radius} px`;$('#brushPanelLabel').textContent=tool==='eraser'?'橡皮笔尖':'画笔笔尖'}
  function renderStudioPalette(){
    const root=$('#studioPalette');if(!root)return;root.innerHTML='';state.palette.forEach((entry,i)=>{const sw=document.createElement('div');sw.className='studio-swatch'+(editingId===entry.id?' active':'');sw.style.backgroundColor=entry.color;sw.style.color=contrastText(entry.color);sw.append(document.createTextNode(i.toString(16).toUpperCase()));sw.title=`长按或拖动排序 · ${entry.color}`;sw.dataset.id=entry.id;sw.dataset.index=i;sw.onclick=()=>{if(Date.now()>=paletteDragSuppressClickUntil)selectEditingColor(entry.id)};root.append(sw)})
  }
  function paletteRects(){const rects=new Map();$$('[data-id]',$('#studioPalette')).forEach(el=>{const r=el.getBoundingClientRect();if(r.width&&r.height)rects.set(`${el.parentElement.id}:${el.dataset.id}`,r)});return rects}
  function animatePaletteReorder(before){$$('[data-id]',$('#studioPalette')).forEach(el=>{const old=before.get(`${el.parentElement.id}:${el.dataset.id}`),now=el.getBoundingClientRect();if(!old||!now.width||typeof el.animate!=='function')return;const dx=old.left-now.left,dy=old.top-now.top;if(dx||dy)el.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:190,easing:'cubic-bezier(.2,.8,.2,1)'})})}
  function reorderPaletteLive(id,to){const from=state.palette.findIndex(entry=>entry.id===id);if(from<0||to<0||from===to)return false;const before=paletteRects(),[entry]=state.palette.splice(from,1);state.palette.splice(to,0,entry);renderPalette();animatePaletteReorder(before);return true}
  function bindPaletteReorder(root,selector){let drag=null;const activate=()=>{if(!drag||drag.active)return;drag.active=true;drag.moved=false;beginAction('重新排列颜色');root.setPointerCapture?.(drag.pointerId);root.querySelector(`${selector}[data-id="${drag.id}"]`)?.classList.add('dragging');document.body.classList.add('palette-reordering')},finish=e=>{if(!drag||e.pointerId!==drag.pointerId)return;clearTimeout(drag.timer);if(drag.active){paletteDragSuppressClickUntil=Date.now()+450;document.body.classList.remove('palette-reordering');if(drag.moved)commitAction();else pendingAction=null;renderPalette();if(colorView==='lab')drawLabView();if(colorView==='wheel')drawWheelView()}drag=null};
    root.addEventListener('pointerdown',e=>{if(e.button!==0)return;const item=e.target.closest(selector);if(!item||!root.contains(item))return;drag={pointerId:e.pointerId,id:item.dataset.id,x:e.clientX,y:e.clientY,active:false,moved:false,timer:null,pointerType:e.pointerType};if(e.pointerType==='touch'||e.pointerType==='pen')drag.timer=setTimeout(activate,380)});
    root.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;const distance=Math.hypot(e.clientX-drag.x,e.clientY-drag.y);if(!drag.active){if(drag.pointerType==='mouse'&&distance>4)activate();else if(distance>10){clearTimeout(drag.timer);drag=null}return}e.preventDefault();const items=$$(selector,root);if(!items.length)return;let nearest=null,best=Infinity;items.forEach(item=>{const r=item.getBoundingClientRect(),d=Math.hypot(e.clientX-(r.left+r.width/2),e.clientY-(r.top+r.height/2));if(d<best){best=d;nearest=item}});if(nearest&&nearest.dataset.id!==drag.id){const to=state.palette.findIndex(entry=>entry.id===nearest.dataset.id);if(reorderPaletteLive(drag.id,to)){drag.moved=true;root.querySelector(`${selector}[data-id="${drag.id}"]`)?.classList.add('dragging')}}});
    root.addEventListener('pointerup',finish);root.addEventListener('pointercancel',finish);root.addEventListener('contextmenu',e=>{if(e.target.closest(selector))e.preventDefault()})
  }
  function currentTool(){return altEyedropper?'eyedropper':state.tool}
  function toolButtonActive(button){if(button.dataset.tool)return button.dataset.tool===currentTool();return button.dataset.panel===activePanel||button.dataset.action==='symmetry'&&state.symmetry!=='none'}
  function updateStatus(){const tool=currentTool(),label=tool==='fill'?(fillMode==='selection'?'选区填充':'邻接填充'):{pen:'画笔',eraser:'橡皮',eyedropper:'取色',line:'直线',rect:'矩形',circle:'圆形',select:'选区'}[tool]||tool;$('#statusTool').textContent=label;const c=paletteColor(state.currentId)||candidate||DEFAULT_COLOR;$('#statusColor i').style.backgroundColor=c;$('#statusColor b').textContent=c.toUpperCase();$('#zoomValue').textContent=`${Math.round(zoom*100)}%`;$$('.tool').forEach(b=>b.classList.toggle('active',toolButtonActive(b)));$$('[data-symmetry]').forEach(b=>b.classList.toggle('active',b.dataset.symmetry===state.symmetry))}
  function renderAll(){renderCanvas();renderPalette();renderSelection();renderHistory();renderBrushControls();updateStatus();applyTransform()}

  function updateTransparencyMask(){const w=dom.viewport.clientWidth,h=dom.viewport.clientHeight,size=ART_SIZE*zoom,left=w/2+panX-size/2,top=h/2+panY-size/2,clipLeft=clamp(left,0,w),clipTop=clamp(top,0,h),clipRight=clamp(w-left-size,0,w),clipBottom=clamp(h-top-size,0,h);dom.pattern.style.clipPath=`inset(${clipTop}px ${clipRight}px ${clipBottom}px ${clipLeft}px)`}
  function applyTransform(){dom.transform.style.transform=`translate(${panX-ART_SIZE*zoom/2}px,${panY-ART_SIZE*zoom/2}px) scale(${zoom})`;updateTransparencyMask();updateStatus()}
  function setZoom(next,clientX=null,clientY=null){next=clamp(next,MIN_ZOOM,MAX_ZOOM);if(next===zoom)return;const r=dom.viewport.getBoundingClientRect(),cx=(clientX??(r.left+r.width/2))-r.left-r.width/2,cy=(clientY??(r.top+r.height/2))-r.top-r.height/2;const artX=(cx-panX)/zoom,artY=(cy-panY)/zoom;panX=cx-artX*next;panY=cy-artY*next;zoom=next;applyTransform()}
  function resetView(){const r=dom.viewport.getBoundingClientRect();zoom=clamp(Math.min(1,(r.width-48)/ART_SIZE,(r.height-48)/ART_SIZE),MIN_ZOOM,1);panX=panY=0;applyTransform()}

  function symmetryPoints(x,y){const pts=[[x,y]],mx=SIZE-1-x,my=SIZE-1-y,c=(SIZE-1)/2,dx=x-c,dy=y-c;if(state.symmetry==='horizontal'||state.symmetry==='both')pts.push([mx,y]);if(state.symmetry==='vertical'||state.symmetry==='both')pts.push([x,my]);if(state.symmetry==='both')pts.push([mx,my]);if(state.symmetry==='rotate4'||state.symmetry==='rotate8'){pts.push([Math.round(c-dy),Math.round(c+dx)],[Math.round(c-dx),Math.round(c-dy)],[Math.round(c+dy),Math.round(c-dx)])}if(state.symmetry==='rotate8')pts.push([Math.round(c+dy),Math.round(c+dx)],[Math.round(c-dy),Math.round(c-dx)],[Math.round(c+dx),Math.round(c-dy)],[Math.round(c-dx),Math.round(c+dy)]);const seen=new Set();return pts.map(([x,y])=>({x,y})).filter(p=>p.x>=0&&p.y>=0&&p.x<SIZE&&p.y<SIZE&&!seen.has(`${p.x},${p.y}`)&&seen.add(`${p.x},${p.y}`))}
  function linePoints(x0,y0,x1,y1){const out=[],dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1;let err=dx+dy;while(true){out.push({x:x0,y:y0});if(x0===x1&&y0===y1)break;const e=2*err;if(e>=dy){err+=dy;x0+=sx}if(e<=dx){err+=dx;y0+=sy}}return out}
  function rectPoints(a,b,hollow=false){const out=[];for(let y=Math.min(a.y,b.y);y<=Math.max(a.y,b.y);y++)for(let x=Math.min(a.x,b.x);x<=Math.max(a.x,b.x);x++)if(!hollow||x===Math.min(a.x,b.x)||x===Math.max(a.x,b.x)||y===Math.min(a.y,b.y)||y===Math.max(a.y,b.y))out.push({x,y});return out}
  function circlePoints(a,b,hollow=false){const out=[],r=Math.hypot(b.x-a.x,b.y-a.y),rsq=r*r;for(let y=Math.ceil(-r);y<=Math.floor(r);y++)for(let x=Math.ceil(-r);x<=Math.floor(r);x++){const d=x*x+y*y;if((!hollow&&d<=rsq)||(hollow&&Math.abs(d-rsq)<=Math.max(1,r)))out.push({x:a.x+x,y:a.y+y})}return out}
  function shapePoints(tool,a,b,hollow=false){if(tool==='line')return linePoints(a.x,a.y,b.x,b.y);if(tool==='rect')return rectPoints(a,b,hollow);if(tool==='circle')return circlePoints(a,b,hollow);return[]}
  const brushOffsetCache=new Map();
  function brushOffsets(){const {shape,radius}=brushSettings(),key=`${shape}:${radius}`;if(brushOffsetCache.has(key))return brushOffsetCache.get(key);const offsets=[];for(let y=-radius;y<=radius;y++)for(let x=-radius;x<=radius;x++)if(shape==='square'||x*x+y*y<=radius*radius)offsets.push({x,y});brushOffsetCache.set(key,offsets);return offsets}
  function paintPoint(x,y,id=state.currentId,useBrush=false){const offsets=useBrush?brushOffsets():[{x:0,y:0}],seen=new Set();symmetryPoints(x,y).forEach(center=>offsets.forEach(offset=>{const px=center.x+offset.x,py=center.y+offset.y,key=`${px},${py}`;if(px>=0&&py>=0&&px<SIZE&&py<SIZE&&!seen.has(key)&&pixelEditable(px,py)){seen.add(key);state.pixels[indexOf(px,py)]=id}}))}
  function paintLine(a,b,id){linePoints(a.x,a.y,b.x,b.y).forEach(p=>paintPoint(p.x,p.y,id,true));renderCanvas()}
  function flood(x,y,newId){if(!pixelEditable(x,y))return;const target=state.pixels[indexOf(x,y)];if(target===newId)return;const q=[[x,y]],seen=new Set();while(q.length){const [cx,cy]=q.pop(),key=`${cx},${cy}`;if(cx<0||cy<0||cx>=SIZE||cy>=SIZE||seen.has(key)||!pixelEditable(cx,cy)||state.pixels[indexOf(cx,cy)]!==target)continue;seen.add(key);state.pixels[indexOf(cx,cy)]=newId;q.push([cx+1,cy],[cx-1,cy],[cx,cy+1],[cx,cy-1])}}
  function canvasPos(e,clampToCanvas=false){const r=dom.canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*SIZE),y=Math.floor((e.clientY-r.top)/r.height*SIZE);if(clampToCanvas)return{x:clamp(x,0,SIZE-1),y:clamp(y,0,SIZE-1)};return x>=0&&y>=0&&x<SIZE&&y<SIZE?{x,y}:null}

  const pointers=new Map();let panSession=null,pinchSession=null,suppressCanvasMenu=false;
  function updateDrawingCursor(){dom.viewport.classList.toggle('drawing',!!drawSession&&!drawSession.kind)}
  function pointerDown(e){
    pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});dom.viewport.setPointerCapture?.(e.pointerId);
    if(e.button===2){e.preventDefault();suppressCanvasMenu=true;panSession={x:e.clientX,y:e.clientY,panX,panY};return}
    if(e.pointerType==='touch'&&pointers.size===2){if(drawSession){if(['line','rect','circle'].includes(drawSession.tool)){drawSession=null;dom.preview.innerHTML='';updateDrawingCursor()}else finishDraw(e,drawSession.last)}const p=[...pointers.values()],cx=(p[0].x+p[1].x)/2,cy=(p[0].y+p[1].y)/2;pinchSession={dist:Math.max(1,Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y)),zoom,cx,cy,panX,panY};return}
    if(e.button!==0||!e.target.closest('#canvas'))return;const pos=canvasPos(e);if(!pos)return;
    if(paste){drawSession={kind:'paste',start:pos,last:pos,originX:paste.x,originY:paste.y};return}
    const tool=e.altKey?'eyedropper':currentTool();if(['pen','fill','line','rect','circle'].includes(tool))prepareCandidateForDrawing();drawSession={start:pos,last:pos,end:pos,shift:e.shiftKey,tool};
    if(tool==='pen'||tool==='eraser'){const connect=tool==='pen'&&e.shiftKey&&lastPenEnd;beginAction(connect?'连接上一笔':tool==='pen'?'绘画像素':'擦除像素');if(connect)paintLine(lastPenEnd,pos,state.currentId);else{paintPoint(pos.x,pos.y,tool==='eraser'?null:state.currentId,true);renderCanvas()}}
    else if(tool==='fill'){beginAction(fillMode==='selection'?(selection.size?'填充选区':'填充画布'):'邻接填充');if(fillMode==='selection'){if(selection.size)selection.forEach(i=>state.pixels[i]=state.currentId);else state.pixels.fill(state.currentId)}else flood(pos.x,pos.y,state.currentId);renderCanvas();commitAction();drawSession=null}
    else if(tool==='eyedropper'){const id=state.pixels[indexOf(pos.x,pos.y)];if(id)selectEditingColor(id);drawSession=null}
    else if(tool==='select'){if(!e.shiftKey)selection.clear();selection.add(indexOf(pos.x,pos.y));renderSelection()}
    updateDrawingCursor()
  }
  function pointerMove(e){
    if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const insidePos=canvasPos(e),pos=insidePos||(drawSession?.tool==='select'&&selectionMode()==='rect'?canvasPos(e,true):null);$('#statusCursor').textContent=pos?`${pos.x}, ${pos.y}`:'—, —';
    if(pinchSession&&pointers.size>=2){const p=[...pointers.values()],dist=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),cx=(p[0].x+p[1].x)/2,cy=(p[0].y+p[1].y)/2;zoom=clamp(pinchSession.zoom*dist/pinchSession.dist,MIN_ZOOM,MAX_ZOOM);panX=pinchSession.panX+(cx-pinchSession.cx);panY=pinchSession.panY+(cy-pinchSession.cy);applyTransform();return}
    if(panSession){panX=panSession.panX+e.clientX-panSession.x;panY=panSession.panY+e.clientY-panSession.y;applyTransform();return}
    if(!drawSession)return;if(!pos){if(drawSession.tool==='pen'||drawSession.tool==='eraser')drawSession.last=null;return}
    if(drawSession.kind==='paste'){paste.x=clamp(drawSession.originX+pos.x-drawSession.start.x,-paste.w+1,SIZE-1);paste.y=clamp(drawSession.originY+pos.y-drawSession.start.y,-paste.h+1,SIZE-1);renderSelection();return}
    if(drawSession.tool==='pen'||drawSession.tool==='eraser'){const id=drawSession.tool==='eraser'?null:state.currentId;if(drawSession.last)paintLine(drawSession.last,pos,id);else{paintPoint(pos.x,pos.y,id,true);renderCanvas()}drawSession.last=pos;drawSession.end=pos}
    else if(['line','rect','circle'].includes(drawSession.tool))renderPreview(shapePoints(drawSession.tool,drawSession.start,pos,e.shiftKey));
    else if(drawSession.tool==='select'){
      if(selectionMode()==='free'){selection.add(indexOf(pos.x,pos.y))}else{selection.clear();rectPoints(drawSession.start,pos).forEach(p=>selection.add(indexOf(p.x,p.y)))}renderSelection()
    }
  }
  function finishDraw(e,position=null){
    const pos=position||canvasPos(e)||drawSession?.end||drawSession?.last;if(drawSession&&!drawSession.kind){const tool=drawSession.tool;if(pos&&['line','rect','circle'].includes(tool)){beginAction(`绘制${{line:'直线',rect:'矩形',circle:'圆形'}[tool]}`);shapePoints(tool,drawSession.start,pos,e.shiftKey).forEach(p=>paintPoint(p.x,p.y));renderCanvas();dom.preview.innerHTML='';commitAction()}else if(tool==='pen'||tool==='eraser'){if(tool==='pen'&&pos)lastPenEnd={...pos};commitAction()}}drawSession=null;updateDrawingCursor()
  }
  function pointerUp(e){finishDraw(e);pointers.delete(e.pointerId);if(e.button===2){panSession=null;setTimeout(()=>suppressCanvasMenu=false,0)}if(pointers.size<2)pinchSession=null}
  function selectionMode(){return $('[data-select-mode].active')?.dataset.selectMode||'rect'}

  function boundsOfSelection(){if(!selection.size)return null;const xs=[...selection].map(i=>i%SIZE),ys=[...selection].map(i=>Math.floor(i/SIZE));return {minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
  function copySelection(){const b=boundsOfSelection();if(!b)return toast('请先建立选区');const cells=Array.from({length:b.maxY-b.minY+1},()=>Array(b.maxX-b.minX+1));selection.forEach(i=>{const x=i%SIZE,y=Math.floor(i/SIZE);cells[y-b.minY][x-b.minX]={selected:true,id:state.pixels[i]}});clipboard={w:cells[0].length,h:cells.length,cells};toast('已复制选区')}
  function cutSelection(move=false){if(!selection.size)return toast('请先建立选区');copySelection();beginAction(move?'移动选区':'剪切选区');selection.forEach(i=>state.pixels[i]=null);renderCanvas();if(!move)commitAction();beginPaste();}
  function beginPaste(){if(!clipboard)return toast('剪贴板为空');const b=boundsOfSelection();paste={...clone(clipboard),x:b?.minX||0,y:b?.minY||0};selection.clear();renderSelection()}
  function placePaste(){if(!paste)return;if(!pendingAction)beginAction('放置选区');paste.cells.forEach((row,y)=>row.forEach((cell,x)=>{if(cell?.selected){const tx=paste.x+x,ty=paste.y+y;if(tx>=0&&ty>=0&&tx<SIZE&&ty<SIZE)state.pixels[indexOf(tx,ty)]=cell.id}}));paste=null;renderCanvas();renderSelection();commitAction()}
  function deleteSelectionPixels(){if(!selection.size)return;beginAction('删除选区像素');selection.forEach(i=>state.pixels[i]=null);lastPenEnd=null;renderCanvas();commitAction()}
  function selectionAction(action){if(action==='copy')copySelection();if(action==='cut')cutSelection();if(action==='move')cutSelection(true);if(action==='paste')beginPaste();if(action==='place')placePaste();if(action==='clear'){if(pendingAction?.label==='移动选区')cancelAction();selection.clear();paste=null;renderSelection()}}

  function openPanel(id,forceOpen=false){const same=activePanel===id&&dom.optionDock.classList.contains('open');activePanel=forceOpen?id:(same?null:id);dom.optionDock.classList.toggle('open',!!activePanel);$$('.option-panel').forEach(p=>p.classList.toggle('active',p.id===activePanel));$$('.tool[data-panel]').forEach(b=>b.classList.toggle('active',toolButtonActive(b)))}
  function setTool(tool){if(pendingAction?.label==='移动选区'&&tool!==state.tool){cancelAction();paste=null}if(tool!=='pen')lastPenEnd=null;state.tool=tool;if(tool!=='select'&&activePanel==='selectionPanel')openPanel('selectionPanel');if(tool!=='fill'&&activePanel==='fillPanel')openPanel('fillPanel');if(!['pen','eraser'].includes(tool)&&activePanel==='brushPanel')openPanel('brushPanel');renderBrushControls();updateStatus();console.info(`[Pixel Atelier] tool:selected ${tool}`)}

  function nearestConflict(hex,excludeId=null){const lab=colorLab(hex);let best=null;state.palette.forEach(c=>{if(c.id===excludeId)return;const d=deltaE00(lab,colorLab(c.color));if(!best||d<best.distance)best={entry:c,distance:d}});return best}
  function validCandidate(hex,excludeId=null){const conflict=nearestConflict(hex,excludeId);return {valid:!conflict||conflict.distance>=state.minDeltaE,conflict}}
  function sortPalettePerceptually(){state.palette.sort((left,right)=>{const leftLab=colorLab(left.color),rightLab=colorLab(right.color),leftNeutral=Math.hypot(leftLab.a,leftLab.b)<8,rightNeutral=Math.hypot(rightLab.a,rightLab.b)<8;if(leftNeutral!==rightNeutral)return leftNeutral?-1:1;if(leftNeutral)return leftLab.L-rightLab.L||left.id.localeCompare(right.id);const leftHsl=rgbToHsl(hexToRgb(left.color)),rightHsl=rgbToHsl(hexToRgb(right.color));return leftHsl.h-rightHsl.h||leftLab.L-rightLab.L||rightHsl.s-leftHsl.s||left.id.localeCompare(right.id)})}
  function updateColorTracks(rgb,hsl,lab){
    const cssRgb=color=>`rgb(${Math.round(color.r)} ${Math.round(color.g)} ${Math.round(color.b)})`,setTrack=(id,colors,thumb)=>{const input=$('#'+id);input.style.setProperty('--track-gradient',`linear-gradient(90deg,${colors.join(',')})`);input.style.setProperty('--track-thumb',thumb)};
    setTrack('rgbR',[`rgb(0 ${Math.round(rgb.g)} ${Math.round(rgb.b)})`,`rgb(255 ${Math.round(rgb.g)} ${Math.round(rgb.b)})`],cssRgb(rgb));
    setTrack('rgbG',[`rgb(${Math.round(rgb.r)} 0 ${Math.round(rgb.b)})`,`rgb(${Math.round(rgb.r)} 255 ${Math.round(rgb.b)})`],cssRgb(rgb));
    setTrack('rgbB',[`rgb(${Math.round(rgb.r)} ${Math.round(rgb.g)} 0)`,`rgb(${Math.round(rgb.r)} ${Math.round(rgb.g)} 255)`],cssRgb(rgb));
    const hueColors=[0,60,120,180,240,300,360].map(h=>cssRgb(hslToRgb({h,s:100,l:50}))),hueThumb=cssRgb(hslToRgb({h:hsl.h,s:100,l:50})),saturationColors=[0,25,50,75,100].map(s=>cssRgb(hslToRgb({h:hsl.h,s,l:50})));setTrack('hslH',hueColors,hueThumb);setTrack('hslS',saturationColors,cssRgb(rgb));
    const labColors=[0,25,50,75,100].map(L=>cssRgb(labToRgb({L,a:lab.a,b:lab.b}))),labThumb=cssRgb(labToRgb({L:+$('#labLightness').value,a:lab.a,b:lab.b}));setTrack('labLightness',labColors,labThumb);
    const lightnessColors=[0,25,50,75,100].map(l=>cssRgb(hslToRgb({h:hsl.h,s:hsl.s,l}))),wheelThumb=cssRgb(hslToRgb({h:hsl.h,s:hsl.s,l:+$('#wheelLightness').value}));setTrack('wheelLightness',lightnessColors,wheelThumb);setTrack('hslL',lightnessColors,cssRgb(rgb));
  }
  function setCandidate(hex,source='all'){if(!hexToRgb(hex))return;candidate=hex.toLowerCase();const rgb=hexToRgb(candidate),hsl=rgbToHsl(rgb),lab=rgbToLab(rgb);if(source!=='lab'||!labCursor)labCursor=lab;if(!['hsl','wheel'].includes(source)||!wheelCursor)wheelCursor=hsl;if(source==='selection'){const labLightness=$('#labLightness'),wheelLightness=$('#wheelLightness');labLightness.value=Math.round(lab.L);labLightness.nextElementSibling.textContent=labLightness.value;wheelLightness.value=Math.round(hsl.l);wheelLightness.nextElementSibling.textContent=wheelLightness.value+'%'}$('#candidatePreview span').style.backgroundColor=candidate;$('#candidatePreview b').textContent=candidate.toUpperCase();$('#hexInput').value=candidate;$('#nativeColor').value=candidate;
    if(source!=='rgb'){[['rgbR',rgb.r],['rgbG',rgb.g],['rgbB',rgb.b]].forEach(([id,v])=>{const input=$('#'+id);input.value=Math.round(v);input.nextElementSibling.textContent=Math.round(v)})}
    if(source!=='hsl'){[['hslH',hsl.h,'°'],['hslS',hsl.s,'%'],['hslL',hsl.l,'%']].forEach(([id,v,u])=>{const input=$('#'+id);input.value=Math.round(v);input.nextElementSibling.textContent=Math.round(v)+u})}
    if(source!=='lab'){const labValue=value=>Math.abs(value)<.05?'0.0':value.toFixed(1);$('#labLInput').value=labValue(lab.L);$('#labAInput').value=labValue(lab.a);$('#labBInput').value=labValue(lab.b)}updateColorTracks(rgb,hsl,lab);
    const updateCheck=editingId?validCandidate(candidate,editingId):{valid:false,conflict:null},addCheck=validCandidate(candidate,null),activeCheck=editingId?updateCheck:addCheck,v=$('#colorValidation');candidateIsValid=activeCheck.valid;v.className='validation '+(activeCheck.valid?'ok':'error');if(activeCheck.valid)v.textContent=editingId?(addCheck.valid?'可更新选中颜色，也可添加为新颜色':'可更新选中颜色'):'可添加到调色板';else{const conflict=activeCheck.conflict;v.textContent=conflict?`与颜色 ${state.palette.indexOf(conflict.entry).toString(16).toUpperCase()} 仅相差 ΔE00 ${conflict.distance.toFixed(2)}`:'请先从调色板选择要更新的颜色'}$('#updateSelectedColor').disabled=!editingId||!updateCheck.valid;$('#deleteSelectedColor').disabled=!editingId;$('#addCandidateColor').disabled=false;if(colorView==='lab')drawLabView();if(colorView==='wheel')drawWheelView()}
  function syncColorEditorSelection(){const entry=state.palette.find(item=>item.id===state.currentId)||state.palette[0]||null;state.currentId=entry?.id||null;editingId=entry?.id||null;colorDragPreview=false;labCursor=null;wheelCursor=null;setCandidate(entry?.color||DEFAULT_COLOR,'selection');renderPalette();renderStudioPalette()}
  function selectEditingColor(id){editingId=id;state.currentId=id;setCandidate(paletteColor(id),'selection');renderPalette();renderStudioPalette()}
  function applyCandidate(mode=editingId?'update':'add'){const targetId=mode==='update'?editingId:null,target=targetId?state.palette.find(c=>c.id===targetId):null;if(mode==='update'&&!target){syncColorEditorSelection();return false}const check=validCandidate(candidate,targetId);if(!check.valid)return false;if(mode==='update'){beginAction('修改调色板颜色');target.color=candidate;state.currentId=targetId}else{if(state.palette.length>=16)return false;beginAction('添加调色板颜色');const item={id:uid(),color:candidate};state.palette.push(item);state.currentId=item.id;editingId=item.id}sortPalettePerceptually();commitAction();renderCanvas();renderSelection();renderPalette();renderStudioPalette();updateStatus();setCandidate(candidate,'selection');toast(mode==='update'?'颜色已更新':'颜色已添加');return true}
  function prepareCandidateForDrawing(){const selected=paletteColor(state.currentId);if(candidate===selected)return;const existing=state.palette.find(entry=>entry.color.toLowerCase()===candidate);if(existing){selectEditingColor(existing.id);return}const revert=message=>{if(selected)setCandidate(selected,'selection');toast(message)};if(state.palette.length>=16){revert('调色板已满，已回退到选中颜色绘制');return}if(!validCandidate(candidate,null).valid){revert(`候选颜色不满足最小 ΔE00 ${state.minDeltaE}，已回退到选中颜色`);return}applyCandidate('add')}
  function deleteColor(id){const used=state.pixels.filter(v=>v===id).length;if(used&&!confirm(`这个颜色正在被 ${used} 个像素使用。删除后这些像素会变为透明，确定继续吗？`))return;if(!used&&!confirm('确定删除这个颜色吗？'))return;beginAction('删除调色板颜色');selection.clear();state.pixels.forEach((v,i)=>{if(v===id){state.pixels[i]=null;selection.add(i)}});state.palette=state.palette.filter(c=>c.id!==id);if(state.currentId===id)state.currentId=state.palette[0]?.id||null;if(editingId===id)editingId=null;commitAction();renderAll();setCandidate(paletteColor(state.currentId)||DEFAULT_COLOR,'selection');toast(used?`已删除颜色并选中 ${used} 个透明像素`:'已删除颜色')}
  function clearPalette(){if(!state.palette.length)return;if(!confirm('确定清空调色板吗？画布中的所有像素也会变为透明。'))return;beginAction('清空调色板');state.palette=[];state.pixels.fill(null);state.currentId=null;editingId=null;lastPenEnd=null;selection.clear();paste=null;commitAction();renderAll();syncColorEditorSelection();toast('调色板已清空')}
  function labFromCanvas(e){const r=$('#labCanvas').getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;return {L:+$('#labLightness').value,a:x*220-110,b:110-y*220}}
  function hslFromWheel(e){const c=$('#wheelCanvas'),r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*c.width-c.width/2,y=(e.clientY-r.top)/r.height*c.height-c.height/2,R=c.width/2-3,s=clamp(Math.hypot(x,y)/R,0,1);return {h:(Math.atan2(y,x)*180/Math.PI+360)%360,s:s*100,l:+$('#wheelLightness').value}}
  function drawLabView(){
    const c=$('#labCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height,L=+$('#labLightness').value,baseKey=String(L);if(c.dataset.baseKey!==baseKey){const base=cacheValue(labBaseCache,baseKey,()=>buildModelCanvas(LAB_MODEL,i=>labToRgb({L,a:LAB_MODEL.a[i],b:LAB_MODEL.b[i]})));ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.drawImage(base,0,0,w,h);c.dataset.baseKey=baseKey}const entries=displayPalette(),restrictionKey=`${state.minDeltaE}|${L}|${paletteSignature(entries)}`,regions=cacheValue(labRestrictionCache,restrictionKey,()=>buildLabRestrictions(L,w,h,entries));renderRestrictionLayer($('#labRestrictionLayer'),restrictionKey,regions);const markers=entries.map((entry,i)=>{const lab=entry.previewLab||colorLab(entry.color);return Math.abs(lab.L-L)<=18?{x:(lab.a+110)/220*w,y:(110-lab.b)/220*h,color:entry.color,label:i.toString(16).toUpperCase(),active:entry.id===editingId}:null}).filter(Boolean);renderMarkerLayer($('#labMarkerLayer'),`${restrictionKey}|${editingId||''}`,markers);const cursor=labCursor||rgbToLab(hexToRgb(candidate));updateCandidateMarker($('#labCandidateMarker'),(cursor.a+110)/220*w,(110-cursor.b)/220*h,cursor.a>=-110&&cursor.a<=110&&cursor.b>=-110&&cursor.b<=110&&!(colorDragPreview&&editingId))
  }
  function drawWheelView(){
    const c=$('#wheelCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h/2,R=Math.min(w,h)/2-3,L=+$('#wheelLightness').value,baseKey=String(L);if(c.dataset.baseKey!==baseKey){const base=cacheValue(wheelBaseCache,baseKey,()=>buildModelCanvas(WHEEL_MODEL,i=>WHEEL_MODEL.inside[i]?hslToRgb({h:WHEEL_MODEL.hue[i],s:WHEEL_MODEL.saturation[i],l:L}):null));ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.drawImage(base,0,0,w,h);c.dataset.baseKey=baseKey}const entries=displayPalette(),restrictionKey=`${state.minDeltaE}|${L}|${paletteSignature(entries)}`,regions=cacheValue(wheelRestrictionCache,restrictionKey,()=>buildWheelRestrictions(L,w,h,entries));renderRestrictionLayer($('#wheelRestrictionLayer'),restrictionKey,regions);const markers=entries.map((entry,i)=>{const hsl=entry.previewHsl||rgbToHsl(hexToRgb(entry.color));if(Math.abs(hsl.l-L)>18)return null;const angle=hsl.h*Math.PI/180,r=hsl.s/100*R;return{x:cx+Math.cos(angle)*r,y:cy+Math.sin(angle)*r,color:entry.color,label:i.toString(16).toUpperCase(),active:entry.id===editingId}}).filter(Boolean);renderMarkerLayer($('#wheelMarkerLayer'),`${restrictionKey}|${editingId||''}`,markers);const cursor=wheelCursor||rgbToHsl(hexToRgb(candidate)),angle=cursor.h*Math.PI/180,r=cursor.s/100*R;updateCandidateMarker($('#wheelCandidateMarker'),cx+Math.cos(angle)*r,cy+Math.sin(angle)*r,cursor.s>=0&&cursor.s<=100&&!(colorDragPreview&&editingId))
  }

  function cleanupImport(){if(importState?.url)URL.revokeObjectURL(importState.url);importState=null}
  const IMPORT_ALGORITHM_NOTES={none:'使用感知色差量化，不主动移动颜色或改变区域关系。',shift:'利用剩余色位，在允许偏移内恢复差距最大的被合并颜色。',contrast:'固定量化调色板，通过区域邻接图重新分配颜色，优先拉开接触区域。',balanced:'先用偏移恢复颜色，再通过区域邻接图兼顾原色准确度与边界区分。'};
  function syncImportControls(){if(!importState)return;const preview=$('#toggleImportPreview'),importDelta=$('#importMinDeltaE');preview.textContent=importState.preview?'关闭预览':'开启预览';preview.classList.toggle('active',importState.preview);preview.setAttribute('aria-pressed',String(importState.preview));if(document.activeElement!==importDelta){importDelta.value=state.minDeltaE;importDelta.classList.remove('invalid')}$('#importAlgorithm').value=importState.algorithm;$$('.import-algorithm-option').forEach(label=>label.hidden=!label.dataset.algorithms.split(' ').includes(importState.algorithm));[['importColorOffset',importState.maxOffset,''],['importContrastTarget',importState.contrastTarget,''],['importContrastStrength',importState.contrastStrength,'%'],['importRegionThreshold',importState.regionThreshold,'']].forEach(([id,value,suffix])=>{const input=$('#'+id);input.value=value;input.nextElementSibling.textContent=Number(value).toFixed(value%1?1:0)+suffix});$('#importAlgorithmNote').textContent=IMPORT_ALGORITHM_NOTES[importState.algorithm];const result=importState.result,stats=result?.spatialStats,details=result?` · ${result.palette.length} 色${result.recoveredCount?` · 偏移恢复 ${result.recoveredCount}`:''}${stats?.reassignedRegions?` · 调整 ${stats.reassignedRegions} 区域`:''}`:'';$('#importPreviewHint').textContent=importState.preview?`最终 45×45 量化预览${details}`:'拖动图片调整位置，滚轮或滑块缩放'}
  function openImagePicker(){const input=$('#importImageFile');input.value='';input.click()}
  function loadImportImage(file){if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{cleanupImport();const fit=Math.min(450/img.width,450/img.height);importState={img,url,fit,multiplier:1,x:225,y:225,drag:null,preview:false,algorithm:'none',maxOffset:8,contrastTarget:12,contrastStrength:65,regionThreshold:3,result:null};$('#importScale').value=100;$('#importScale').nextElementSibling.textContent='100%';syncImportControls();dom.importDialog.showModal();drawImportPreview()};img.onerror=()=>{URL.revokeObjectURL(url);toast('无法读取这张图片，请换一种格式或文件')};img.src=url}
  function leaveImportPreview(){if(!importState?.preview)return;importState.preview=false;importState.result=null;syncImportControls()}
  function drawImportPreview(){if(!importState)return;const c=$('#importPreview'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(importState.preview&&importState.result){ctx.imageSmoothingEnabled=false;const scale=c.width/SIZE,colors=new Map(importState.result.palette.map(entry=>[entry.id,entry.color]));importState.result.pixels.forEach((id,i)=>{const color=colors.get(id);if(!color)return;ctx.fillStyle=color;ctx.fillRect(i%SIZE*scale,Math.floor(i/SIZE)*scale,scale,scale)});return}ctx.imageSmoothingEnabled=true;const s=importState.fit*importState.multiplier,w=importState.img.width*s,h=importState.img.height*s;ctx.drawImage(importState.img,importState.x-w/2,importState.y-h/2,w,h)}
  function fitImport(){if(!importState)return;leaveImportPreview();importState.multiplier=1;importState.x=importState.y=225;$('#importScale').value=100;$('#importScale').nextElementSibling.textContent='100%';drawImportPreview()}
  function importPixels(){const off=document.createElement('canvas');off.width=off.height=SIZE;const ctx=off.getContext('2d',{willReadFrequently:true}),scale=SIZE/450,s=importState.fit*importState.multiplier*scale,w=importState.img.width*s,h=importState.img.height*s;ctx.clearRect(0,0,SIZE,SIZE);ctx.drawImage(importState.img,importState.x*scale-w/2,importState.y*scale-h/2,w,h);return ctx.getImageData(0,0,SIZE,SIZE).data}
  function weightedMedoid(members){
    const total=members.reduce((sum,item)=>sum+item.weight,0),centroid=members.reduce((sum,item)=>({L:sum.L+item.lab.L*item.weight,a:sum.a+item.lab.a*item.weight,b:sum.b+item.lab.b*item.weight}),{L:0,a:0,b:0});centroid.L/=total;centroid.a/=total;centroid.b/=total;
    const shortlist=(members.length<=128?members:[...members].sort((a,b)=>deltaE00(a.lab,centroid)-deltaE00(b.lab,centroid)||a.color.localeCompare(b.color)).slice(0,32));let best=null,bestCost=Infinity;shortlist.forEach(candidate=>{let cost=0;for(const item of members){const d=deltaE00(item.lab,candidate.lab);cost+=item.weight*d*d;if(cost>bestCost)break}if(cost<bestCost-1e-9||Math.abs(cost-bestCost)<=1e-9&&candidate.color<(best?.color||'')){best=candidate;bestCost=cost}});return {color:best.color,rgb:best.rgb,lab:best.lab,weight:total}
  }
  function enforcePaletteSeparation(samples,centers){
    const unique=new Map();samples.forEach(sample=>{const color=rgbToHex(sample.rgb.r,sample.rgb.g,sample.rgb.b),item=unique.get(color);if(item)item.weight+=sample.weight;else unique.set(color,{color,rgb:hexToRgb(color),lab:colorLab(color),weight:sample.weight})});
    let clusters=centers.map(center=>({members:[],rep:{color:rgbToHex(center.rgb.r,center.rgb.g,center.rgb.b),rgb:hexToRgb(rgbToHex(center.rgb.r,center.rgb.g,center.rgb.b)),lab:null,weight:0}}));clusters.forEach(cluster=>cluster.rep.lab=rgbToLab(cluster.rep.rgb));unique.forEach(item=>{let best=0,distance=Infinity;clusters.forEach((cluster,i)=>{const d=deltaE00(item.lab,cluster.rep.lab);if(d<distance){distance=d;best=i}});clusters[best].members.push(item)});clusters=clusters.filter(cluster=>cluster.members.length).map(cluster=>({members:cluster.members,rep:weightedMedoid(cluster.members)}));
    const before=clusters.length;while(true){let merge=null;for(let i=0;i<clusters.length;i++)for(let j=i+1;j<clusters.length;j++){const a=clusters[i],b=clusters[j],distance=deltaE00(a.rep.lab,b.rep.lab);if(distance>=state.minDeltaE)continue;const penalty=a.rep.weight*b.rep.weight/(a.rep.weight+b.rep.weight)*distance*distance;if(!merge||penalty<merge.penalty-1e-9||Math.abs(penalty-merge.penalty)<=1e-9&&(i<merge.i||i===merge.i&&j<merge.j))merge={i,j,penalty}}if(!merge)break;const members=[...clusters[merge.i].members,...clusters[merge.j].members];clusters[merge.i]={members,rep:weightedMedoid(members)};clusters.splice(merge.j,1)}
    for(let i=0;i<clusters.length;i++)for(let j=i+1;j<clusters.length;j++){const distance=deltaE00(clusters[i].rep.lab,clusters[j].rep.lab);if(distance<state.minDeltaE)throw new Error(`调色板距离修复失败：ΔE00 ${distance.toFixed(3)}`)}return {clusters,mergedCount:before-clusters.length,sources:[...unique.values()]}
  }
  const SHIFT_DIRECTIONS=Array.from({length:40},(_,i)=>{const L=1-2*(i+.5)/40,r=Math.sqrt(Math.max(0,1-L*L)),angle=i*Math.PI*(3-Math.sqrt(5));return {L,a:Math.cos(angle)*r,b:Math.sin(angle)*r}});
  function findShiftedReplacement(source,paletteLabs,maxOffset){
    const evaluate=lab=>{const rgb=labToRgb(lab),color=rgbToHex(rgb.r,rgb.g,rgb.b),actualLab=colorLab(color),offset=deltaE00(source.lab,actualLab);if(offset>maxOffset+.05)return null;let separation=Infinity;for(const existing of paletteLabs){separation=Math.min(separation,deltaE00(actualLab,existing));if(separation<state.minDeltaE-.01)return null}return {color,rgb:hexToRgb(color),lab:actualLab,weight:source.weight,offset,separation}};
    const direct=evaluate(source.lab);if(direct)return direct;let best=null;for(let radius=Math.min(1,maxOffset);radius>0&&radius<=maxOffset+.001;radius=Math.min(maxOffset,radius+1)){for(const direction of SHIFT_DIRECTIONS){const found=evaluate({L:source.lab.L+direction.L*radius,a:source.lab.a+direction.a*radius,b:source.lab.b+direction.b*radius});if(found&&(!best||found.offset<best.offset-.01||Math.abs(found.offset-best.offset)<=.01&&found.separation>best.separation))best=found}if(best)return best;if(radius===maxOffset)break}return null
  }
  function recoverShiftedColors(clusters,sources,maxOffset){
    const assignments=new Map();if(maxOffset<=0||clusters.length>=16)return {clusters,recoveredCount:0,assignments};const recovered=[...clusters],consumed=new Set();let recoveredCount=0;
    while(recovered.length<16){const labs=recovered.map(cluster=>cluster.rep.lab),ranked=sources.filter(source=>!consumed.has(source.color)).map(source=>{let nearest=Infinity;labs.forEach(lab=>nearest=Math.min(nearest,deltaE00(source.lab,lab)));return {source,nearest}}).filter(item=>item.nearest>.25&&item.nearest<state.minDeltaE).sort((a,b)=>b.nearest-a.nearest||b.source.weight-a.source.weight||a.source.color.localeCompare(b.source.color));let replacement=null,selected=null;for(const item of ranked.slice(0,48)){const found=findShiftedReplacement(item.source,labs,maxOffset);if(found){replacement=found;selected=item.source;break}}if(!replacement)break;consumed.add(selected.color);assignments.set(selected.color,recovered.length);recovered.push({members:[selected],rep:replacement});recoveredCount++}
    return {clusters:recovered,recoveredCount,assignments}
  }
  function optimizeSpatialRegions(data,palette,pixels,{regionThreshold=3,contrastTarget=12,contrastStrength=65}={}){
    if(palette.length<2||contrastStrength<=0)return {palette,pixels,spatialStats:{regions:0,reassignedRegions:0}};const count=SIZE*SIZE,parent=new Int32Array(count).fill(-1),labs=Array(count),weights=new Float32Array(count),find=i=>{let root=i;while(parent[root]!==root)root=parent[root];while(parent[i]!==i){const next=parent[i];parent[i]=root;i=next}return root},join=(a,b)=>{a=find(a);b=find(b);if(a!==b)parent[b]=a};
    for(let i=0;i<count;i++){const alpha=data[i*4+3];if(alpha<32)continue;parent[i]=i;weights[i]=alpha/255;labs[i]=rgbToLab({r:data[i*4],g:data[i*4+1],b:data[i*4+2]})}
    for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const i=indexOf(x,y);if(parent[i]<0)continue;if(x+1<SIZE&&parent[i+1]>=0&&deltaE00(labs[i],labs[i+1])<=regionThreshold)join(i,i+1);if(y+1<SIZE&&parent[i+SIZE]>=0&&deltaE00(labs[i],labs[i+SIZE])<=regionThreshold)join(i,i+SIZE)}
    const regionMap=new Map();for(let i=0;i<count;i++){if(parent[i]<0)continue;const root=find(i),region=regionMap.get(root)||{root,pixels:[],weight:0,L:0,a:0,b:0,neighbors:new Map()};region.pixels.push(i);region.weight+=weights[i];region.L+=labs[i].L*weights[i];region.a+=labs[i].a*weights[i];region.b+=labs[i].b*weights[i];regionMap.set(root,region)}const regions=[...regionMap.values()];regions.forEach((region,i)=>{region.index=i;region.lab={L:region.L/region.weight,a:region.a/region.weight,b:region.b/region.weight}});const regionAt=new Int32Array(count).fill(-1);regions.forEach(region=>region.pixels.forEach(i=>regionAt[i]=region.index));const edges=[];
    for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const i=indexOf(x,y),a=regionAt[i];if(a<0)continue;for(const j of [x+1<SIZE?i+1:-1,y+1<SIZE?i+SIZE:-1]){if(j<0)continue;const b=regionAt[j];if(b<0||a===b)continue;const lo=Math.min(a,b),hi=Math.max(a,b),key=`${lo}:${hi}`,left=regions[lo],value=(left.neighbors.get(hi)||0)+1;left.neighbors.set(hi,value);regions[hi].neighbors.set(lo,value)}}regions.forEach(region=>region.neighbors.forEach((boundary,other)=>{if(region.index<other)edges.push({a:region.index,b:other,boundary})}));
    if(!edges.length)return {palette,pixels,spatialStats:{regions:regions.length,reassignedRegions:0}};const paletteLabs=palette.map(entry=>colorLab(entry.color)),paletteDistances=paletteLabs.map(a=>paletteLabs.map(b=>deltaE00(a,b))),fidelity=regions.map(region=>paletteLabs.map(lab=>deltaE00(region.lab,lab))),labels=regions.map((region,i)=>{const counts=new Map();region.pixels.forEach(pixel=>{const id=pixels[pixel],index=palette.findIndex(entry=>entry.id===id);if(index>=0)counts.set(index,(counts.get(index)||0)+1)});let best=0,score=-1;counts.forEach((value,index)=>{if(value>score){score=value;best=index}});if(score<0)fidelity[i].forEach((value,index)=>{if(value<fidelity[i][best])best=index});return best}),initial=[...labels],strength=contrastStrength/100,contrastScale=strength*4,fidelityScale=Math.max(.18,1-strength*.85),ordered=[...regions].sort((a,b)=>{const boundaryA=[...a.neighbors.values()].reduce((sum,n)=>sum+n,0),boundaryB=[...b.neighbors.values()].reduce((sum,n)=>sum+n,0);return boundaryB-boundaryA||b.weight-a.weight});
    const labelCost=(region,label)=>{let cost=fidelity[region.index][label]**2*fidelityScale,totalBoundary=0,contrast=0;region.neighbors.forEach((boundary,other)=>{totalBoundary+=boundary;const deficit=Math.max(0,contrastTarget-paletteDistances[label][labels[other]]);contrast+=boundary*deficit*deficit});return cost+(totalBoundary?contrast/totalBoundary*contrastScale:0)};for(let pass=0;pass<10;pass++){let changed=0;for(const region of ordered){let best=labels[region.index],bestCost=labelCost(region,best);for(let label=0;label<palette.length;label++){if(label===best)continue;const cost=labelCost(region,label);if(cost<bestCost-1e-6||Math.abs(cost-bestCost)<=1e-6&&fidelity[region.index][label]<fidelity[region.index][best]){best=label;bestCost=cost}}if(best!==labels[region.index]){labels[region.index]=best;changed++}}if(!changed)break}
    const output=[...pixels];regions.forEach(region=>region.pixels.forEach(i=>output[i]=palette[labels[region.index]].id));const used=new Set(output.filter(Boolean)),compacted=palette.filter(entry=>used.has(entry.id)),weightedContrast=labelSet=>{let total=0,weight=0;edges.forEach(edge=>{total+=paletteDistances[labelSet[edge.a]][labelSet[edge.b]]*edge.boundary;weight+=edge.boundary});return weight?total/weight:0};return {palette:compacted,pixels:output,spatialStats:{regions:regions.length,reassignedRegions:labels.filter((label,i)=>label!==initial[i]).length,contrastBefore:weightedContrast(initial),contrastAfter:weightedContrast(labels)}}
  }
  function quantizeImage(data,{algorithm='none',maxOffset=8,contrastTarget=12,contrastStrength=65,regionThreshold=3}={}){
    const samples=[],visible=[];for(let i=0;i<SIZE*SIZE;i++){const alpha=data[i*4+3];if(alpha<32)continue;const rgb={r:data[i*4],g:data[i*4+1],b:data[i*4+2]},lab=rgbToLab(rgb),weight=alpha/255;samples.push({i,rgb,lab,weight});visible.push({rgb,lab,weight})}if(!samples.length)return {palette:[],pixels:Array(SIZE*SIZE).fill(null),mergedCount:0};
    const bins=new Map();visible.forEach(s=>{const k=`${s.rgb.r>>3},${s.rgb.g>>3},${s.rgb.b>>3}`;const b=bins.get(k)||{n:0,r:0,g:0,b:0};b.n+=s.weight;b.r+=s.rgb.r*s.weight;b.g+=s.rgb.g*s.weight;b.b+=s.rgb.b*s.weight;bins.set(k,b)});const candidates=[...bins.values()].map(v=>{const rgb={r:v.r/v.n,g:v.g/v.n,b:v.b/v.n};return {rgb,lab:rgbToLab(rgb),weight:v.n}}).sort((a,b)=>b.weight-a.weight);
    if(!candidates.length)return {palette:[],pixels:Array(SIZE*SIZE).fill(null)};
    const centers=[candidates[0]];while(centers.length<16){let best=null;candidates.forEach(c=>{const d=Math.min(...centers.map(x=>deltaE00(c.lab,x.lab)));const score=Math.sqrt(c.weight)*d;if(d>=state.minDeltaE&&(!best||score>best.score))best={...c,score}});if(!best)break;centers.push(best)}
    for(let iter=0;iter<6;iter++){const groups=centers.map(()=>({n:0,r:0,g:0,b:0}));visible.forEach(s=>{let bi=0,bd=Infinity;centers.forEach((c,i)=>{const d=deltaE00(s.lab,c.lab);if(d<bd){bd=d;bi=i}});const g=groups[bi];g.n+=s.weight;g.r+=s.rgb.r*s.weight;g.g+=s.rgb.g*s.weight;g.b+=s.rgb.b*s.weight});groups.forEach((g,i)=>{if(g.n){const rgb={r:g.r/g.n,g:g.g/g.n,b:g.b/g.n},lab=rgbToLab(rgb);if(centers.every((c,j)=>j===i||deltaE00(lab,c.lab)>=state.minDeltaE))centers[i]={...centers[i],rgb,lab}}})}
    const repaired=enforcePaletteSeparation(samples,centers),allowShift=['shift','balanced'].includes(algorithm),restored=allowShift?recoverShiftedColors(repaired.clusters,repaired.sources,maxOffset):{clusters:repaired.clusters,recoveredCount:0,assignments:new Map()};let palette=restored.clusters.map(cluster=>({id:uid(),color:cluster.rep.color})),pixels=Array(SIZE*SIZE).fill(null);samples.forEach(s=>{let bi=restored.assignments.get(rgbToHex(s.rgb.r,s.rgb.g,s.rgb.b)),bd=Infinity;if(bi===undefined){bi=0;restored.clusters.forEach((cluster,i)=>{const d=deltaE00(s.lab,cluster.rep.lab);if(d<bd){bd=d;bi=i}})}pixels[s.i]=palette[bi].id});let spatialStats=null;if(['contrast','balanced'].includes(algorithm)){const optimized=optimizeSpatialRegions(data,palette,pixels,{regionThreshold,contrastTarget,contrastStrength});palette=optimized.palette;pixels=optimized.pixels;spatialStats=optimized.spatialStats}return {palette,pixels,mergedCount:repaired.mergedCount,recoveredCount:restored.recoveredCount,spatialStats};
  }
  function generateImportResult(){if(!importState)return null;return quantizeImage(importPixels(),{algorithm:importState.algorithm,maxOffset:importState.maxOffset,contrastTarget:importState.contrastTarget,contrastStrength:importState.contrastStrength,regionThreshold:importState.regionThreshold})}
  async function refreshImportPreview(){if(!importState)return false;const previewButton=$('#toggleImportPreview'),confirmButton=$('#confirmImport');previewButton.disabled=confirmButton.disabled=true;previewButton.textContent='计算预览…';await new Promise(resolve=>requestAnimationFrame(resolve));try{if(!importState)return false;const result=generateImportResult();if(!result?.palette.length){toast('当前画布范围内没有可见像素');return false}importState.result=result;importState.preview=true;drawImportPreview();return true}catch(error){console.error('[Pixel Atelier] 图片预览失败',error);toast('图片预览失败，请重试或更换图片');return false}finally{previewButton.disabled=confirmButton.disabled=false;if(importState)syncImportControls()}}
  function confirmImport(){if(!importState)return;try{const result=importState.preview&&importState.result?importState.result:generateImportResult();if(!result?.palette.length){toast('当前画布范围内没有可见像素');return}beginAction('导入并量化图片');state.palette=result.palette;state.pixels=result.pixels;lastPenEnd=null;sortPalettePerceptually();state.currentId=state.palette[0]?.id||null;selection.clear();commitAction();renderAll();syncColorEditorSelection();dom.importDialog.close();toast(`已生成 ${state.palette.length} 色像素画${result.mergedCount?`，合并 ${result.mergedCount} 组近似颜色`:''}${result.recoveredCount?`，偏移恢复 ${result.recoveredCount} 色`:''}${result.spatialStats?.reassignedRegions?`，调整 ${result.spatialStats.reassignedRegions} 个区域`:''}`)}catch(error){console.error('[Pixel Atelier] 图片转换失败',error);toast('图片转换失败，请重试或更换图片')}}

  function exportPng(event){const scale=event?.altKey?1:16,c=document.createElement('canvas');c.width=c.height=SIZE*scale;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;state.pixels.forEach((id,i)=>{const color=paletteColor(id);if(!color)return;ctx.fillStyle=color;ctx.fillRect(i%SIZE*scale,Math.floor(i/SIZE)*scale,scale,scale)});c.toBlob(blob=>{if(!blob)return toast('PNG 生成失败');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pixel-atelier-${scale}x-${new Date().toISOString().slice(0,19).replace(/\D/g,'')}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
  function projectJson(){return JSON.stringify({format:'pixel-atelier',version:2,size:SIZE,minDeltaE:state.minDeltaE,palette:state.palette,pixels:state.pixels},null,2)}
  function openData(mode){$('#projectData').value=mode==='export'?projectJson():'';$('#applyProjectData').style.display=mode==='export'?'none':'';$('#copyProjectData').style.display=mode==='export'?'':'none';$('#dataDialog').showModal()}
  function applyProjectData(){try{const data=JSON.parse($('#projectData').value);if(data.format!=='pixel-atelier'||data.version!==2||data.size!==SIZE||!Array.isArray(data.pixels)||data.pixels.length!==SIZE*SIZE||!Array.isArray(data.palette)||data.palette.length>16)throw new Error('项目格式、版本或尺寸不正确');const ids=new Set(),palette=data.palette.map((entry,i)=>{if(!entry||!['string','number'].includes(typeof entry.id))throw new Error(`调色板第 ${i+1} 项缺少有效 ID`);const id=String(entry.id);if(!id||ids.has(id))throw new Error(`调色板第 ${i+1} 项 ID 重复或为空`);const rgb=typeof entry.color==='string'?hexToRgb(entry.color):null;if(!rgb)throw new Error(`调色板第 ${i+1} 项颜色无效`);ids.add(id);return {id,color:rgbToHex(rgb.r,rgb.g,rgb.b)}}),pixels=data.pixels.map((id,i)=>{if(id===null)return null;const normalized=String(id);if(!ids.has(normalized))throw new Error(`第 ${i+1} 个像素引用了不存在的颜色`);return normalized}),minDeltaE=Number.isFinite(+data.minDeltaE)&&+data.minDeltaE>=MIN_DELTA_E?+data.minDeltaE:DEFAULT_MIN_DELTA_E;beginAction('导入项目数据');state.palette=palette;state.pixels=pixels;lastPenEnd=null;sortPalettePerceptually();state.currentId=state.palette[0]?.id||null;state.minDeltaE=minDeltaE;selection.clear();commitAction();renderAll();syncColorEditorSelection();$('#dataDialog').close();toast('项目导入成功')}catch(e){toast(e instanceof Error?e.message:'项目数据无效')}}

  async function copyProjectData(){const textarea=$('#projectData'),text=textarea.value;try{if(window.isSecureContext&&navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);toast('项目数据已复制');return}}catch(error){console.warn('[Pixel Atelier] Clipboard API 不可用，尝试兼容复制',error)}textarea.focus();textarea.select();try{if(document.execCommand?.('copy')){toast('项目数据已复制');return}}catch(error){console.warn('[Pixel Atelier] 兼容复制失败',error)}toast('自动复制不可用，内容已全选，请手动复制')}

  function bindEvents(){
    dom.cancelSelection.addEventListener('pointerdown',e=>e.stopPropagation());
    dom.viewport.addEventListener('contextmenu',e=>{e.preventDefault();suppressCanvasMenu=false});dom.viewport.addEventListener('pointerdown',pointerDown);dom.viewport.addEventListener('pointermove',pointerMove);dom.viewport.addEventListener('pointerup',pointerUp);dom.viewport.addEventListener('pointercancel',pointerUp);
    dom.viewport.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?.1:-.1),e.clientX,e.clientY)},{passive:false});
    const activateToolButton=btn=>{if(btn.dataset.tool){const panelWasOpen=activePanel===btn.dataset.panel,toolWasActive=state.tool===btn.dataset.tool;setTool(btn.dataset.tool);if(btn.dataset.panel&&(!panelWasOpen||toolWasActive))openPanel(btn.dataset.panel)}else if(btn.dataset.action==='symmetry'){if(state.symmetry!=='none'&&activePanel==='symmetryPanel'){beginAction('关闭对称');state.symmetry='none';commitAction();openPanel('symmetryPanel')}else openPanel('symmetryPanel')}else openPanel(btn.dataset.panel)};
    const strip=$('#toolStrip');let stripDrag=null,stripMoved=false,toolTouch=null,suppressToolClickUntil=0;strip.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){const btn=e.target.closest('.tool');if(btn)toolTouch={pointerId:e.pointerId,btn,x:e.clientX,y:e.clientY,moved:false};return}if(e.button!==0)return;stripDrag={pointerId:e.pointerId,x:e.clientX,left:strip.scrollLeft,captured:false};stripMoved=false});strip.addEventListener('pointermove',e=>{if(toolTouch&&e.pointerId===toolTouch.pointerId&&Math.hypot(e.clientX-toolTouch.x,e.clientY-toolTouch.y)>10)toolTouch.moved=true;if(!stripDrag||e.pointerId!==stripDrag.pointerId)return;const dx=e.clientX-stripDrag.x;if(Math.abs(dx)>8){if(!stripDrag.captured){strip.setPointerCapture(e.pointerId);stripDrag.captured=true}stripMoved=true;strip.classList.add('dragging');strip.scrollLeft=stripDrag.left-dx}});strip.addEventListener('pointerup',e=>{if(toolTouch&&e.pointerId===toolTouch.pointerId){suppressToolClickUntil=Date.now()+500;if(!toolTouch.moved){e.preventDefault();activateToolButton(toolTouch.btn)}toolTouch=null;return}if(!stripDrag||e.pointerId!==stripDrag.pointerId)return;if(stripMoved)suppressToolClickUntil=Date.now()+250;stripDrag=null;strip.classList.remove('dragging');setTimeout(()=>stripMoved=false,0)});strip.addEventListener('pointercancel',e=>{if(toolTouch?.pointerId===e.pointerId)toolTouch=null;if(stripDrag?.pointerId===e.pointerId){stripDrag=null;stripMoved=false;strip.classList.remove('dragging')}});strip.addEventListener('click',e=>{if(stripMoved||Date.now()<suppressToolClickUntil){e.preventDefault();e.stopPropagation()}},true);strip.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();strip.scrollLeft+=e.deltaY}},{passive:false});
    bindPaletteReorder($('#studioPalette'),'.studio-swatch');
    $$('.tool').forEach(btn=>btn.onclick=()=>activateToolButton(btn));
    $$('[data-symmetry]').forEach(btn=>btn.onclick=()=>{beginAction('切换对称模式');state.symmetry=state.symmetry===btn.dataset.symmetry?'none':btn.dataset.symmetry;commitAction();updateStatus()});
    $$('[data-select-mode]').forEach(btn=>btn.onclick=()=>{$$('[data-select-mode]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');setTool('select')});
    $$('[data-fill-mode]').forEach(btn=>btn.onclick=()=>{fillMode=btn.dataset.fillMode;$$('[data-fill-mode]').forEach(b=>b.classList.toggle('active',b===btn));setTool('fill');updateStatus()});
    $$('[data-brush-shape]').forEach(btn=>btn.onclick=()=>{state[`${activeBrushTool()}BrushShape`]=btn.dataset.brushShape;renderBrushControls();saveLocal()});$('#brushRadius').oninput=e=>{state[`${activeBrushTool()}BrushRadius`]=clamp(Math.round(+e.target.value||0),0,8);renderBrushControls();saveLocal()};
    $$('[data-selection-action]').forEach(btn=>btn.onclick=()=>selectionAction(btn.dataset.selectionAction));
    $('#undo').onclick=undo;$('#redo').onclick=redo;$('#zoomIn').onclick=()=>setZoom(zoom+.25);$('#zoomOut').onclick=()=>setZoom(zoom-.25);$('#resetView').onclick=resetView;
    $('#toggleGrid').onclick=()=>{beginAction(state.grid?'隐藏网格':'显示网格');state.grid=!state.grid;commitAction();renderCanvas()};
    $('#clearCanvas').onclick=()=>{if(confirm('确定清空整个画布吗？')){beginAction('清空画布');state.pixels.fill(null);selection.clear();lastPenEnd=null;commitAction();renderAll()}};
    $('#themeToggle').onclick=()=>{document.body.classList.toggle('dark-theme');$('#themeToggle').textContent=document.body.classList.contains('dark-theme')?'☼':'☾'};
    $('#importImage').onclick=openImagePicker;$('#importImageFile').onchange=e=>loadImportImage(e.target.files[0]);$('#exportPng').onclick=exportPng;$('#exportData').onclick=()=>openData('export');$('#importData').onclick=()=>openData('import');$('#copyProjectData').onclick=copyProjectData;$('#applyProjectData').onclick=applyProjectData;dom.importDialog.addEventListener('close',cleanupImport);
    $$('.view-tabs button').forEach(btn=>btn.onclick=()=>{colorView=btn.dataset.colorView;$$('.view-tabs button').forEach(b=>b.classList.toggle('active',b===btn));$$('.color-view').forEach(v=>v.classList.toggle('active',v.id===`${colorView}View`));if(colorView==='lab')drawLabView();if(colorView==='wheel')drawWheelView()});
    const requestAddCandidate=()=>{if(state.palette.length>=16){toast('超过颜色数量上限（最多 16 色）');return false}const check=validCandidate(candidate,null);if(!check.valid){toast(`与已有颜色过近，至少需要 ΔE00 ${state.minDeltaE}`);return false}return applyCandidate('add')};$('#updateSelectedColor').onclick=()=>applyCandidate('update');$('#deleteSelectedColor').onclick=()=>{if(editingId)deleteColor(editingId)};$('#clearPalette').onclick=clearPalette;$('#addCandidateColor').onclick=requestAddCandidate;$('#nativePicker').onclick=()=>$('#nativeColor').click();$('#nativeColor').oninput=e=>setCandidate(e.target.value);$('#hexInput').onchange=e=>{let v=e.target.value;if(!v.startsWith('#'))v='#'+v;if(hexToRgb(v))setCandidate(v);else toast('请输入六位 HEX 颜色')};
    const minDeltaInputs=[$('#minDeltaE'),$('#importMinDeltaE')],minDeltaDraftValid=input=>{const value=+input.value,valid=Number.isFinite(value)&&value>=MIN_DELTA_E;input.classList.toggle('invalid',!valid);return valid},syncMinDeltaInputs=()=>minDeltaInputs.forEach(input=>{if(document.activeElement!==input){input.value=state.minDeltaE;input.classList.remove('invalid')}}),commitMinDeltaE=input=>{if(!minDeltaDraftValid(input)){toast(`最小 ΔE00 不能低于内置值 ${MIN_DELTA_E}`);setTimeout(()=>{input.value=state.minDeltaE;input.classList.remove('invalid')},450);return}const value=Math.round(+input.value*10)/10;if(value===state.minDeltaE){syncMinDeltaInputs();return}const refreshPreview=!!importState?.preview;beginAction('调整颜色最小距离');state.minDeltaE=value;commitAction();if(importState)importState.result=null;renderPalette();setCandidate(candidate);syncMinDeltaInputs();if(importState)syncImportControls();if(refreshPreview)refreshImportPreview();toast(`最小 ΔE00 已调整为 ${value}`)};minDeltaInputs.forEach(input=>{input.oninput=()=>minDeltaDraftValid(input);input.onchange=()=>commitMinDeltaE(input);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commitMinDeltaE(input);input.blur()}}});
    ['rgbR','rgbG','rgbB'].forEach(id=>$('#'+id).oninput=e=>{e.target.nextElementSibling.textContent=e.target.value;setCandidate(rgbToHex(+$('#rgbR').value,+$('#rgbG').value,+$('#rgbB').value),'rgb')});
    ['hslH','hslS','hslL'].forEach(id=>$('#'+id).oninput=e=>{e.target.nextElementSibling.textContent=e.target.value+(id==='hslH'?'°':'%');const hsl={h:+$('#hslH').value,s:+$('#hslS').value,l:+$('#hslL').value},rgb=hslToRgb(hsl);wheelCursor=hsl;setCandidate(rgbToHex(rgb.r,rgb.g,rgb.b),'hsl')});
    ['labLInput','labAInput','labBInput'].forEach(id=>$('#'+id).onchange=()=>{const lab={L:+$('#labLInput').value,a:+$('#labAInput').value,b:+$('#labBInput').value},rgb=labToRgb(lab);labCursor=lab;setCandidate(rgbToHex(rgb.r,rgb.g,rgb.b),'lab')});
    $('#labLightness').oninput=e=>{e.target.nextElementSibling.textContent=e.target.value;const base=labCursor||rgbToLab(hexToRgb(candidate));labCursor={...base,L:+e.target.value};colorDragPreview=!!editingId;const rgb=labToRgb(labCursor);setCandidate(rgbToHex(rgb.r,rgb.g,rgb.b),'lab')};$('#labLightness').onchange=()=>{colorDragPreview=false;drawLabView()};$('#wheelLightness').oninput=e=>{e.target.nextElementSibling.textContent=e.target.value+'%';const base=wheelCursor||rgbToHsl(hexToRgb(candidate));wheelCursor={...base,l:+e.target.value};colorDragPreview=!!editingId;const rgb=hslToRgb(wheelCursor);setCandidate(rgbToHex(rgb.r,rgb.g,rgb.b),'wheel')};$('#wheelLightness').onchange=()=>{colorDragPreview=false;drawWheelView()};
    const redrawActiveColorMap=()=>colorView==='lab'?drawLabView():drawWheelView();
    const finishColorInteraction=(e,isClick)=>{colorDragPreview=false;redrawActiveColorMap();if(!isClick||e.shiftKey===e.altKey)return;if(e.shiftKey){requestAddCandidate();return}if(!editingId){toast('请先从调色板选择要更新的颜色');return}if(!applyCandidate('update'))toast(`与已有颜色过近，至少需要 ΔE00 ${state.minDeltaE}`)};
    const cancelColorInteraction=()=>{colorDragPreview=false;redrawActiveColorMap()};
    let labPointer=null;const previewLab=e=>{const lab=labFromCanvas(e),rgb=labToRgb(lab);labCursor=lab;setCandidate(rgbToHex(rgb.r,rgb.g,rgb.b),'lab')};$('#labCanvas').onpointerdown=e=>{if(e.button!==0)return;labPointer={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};colorDragPreview=!!editingId;e.currentTarget.setPointerCapture(e.pointerId);$('#labCandidateMarker').classList.add('dragging');previewLab(e)};$('#labCanvas').onpointermove=e=>{if(e.pointerId!==labPointer?.id)return;if(Math.hypot(e.clientX-labPointer.x,e.clientY-labPointer.y)>4)labPointer.moved=true;previewLab(e)};$('#labCanvas').onpointerup=e=>{if(e.pointerId!==labPointer?.id)return;previewLab(e);const isClick=!labPointer.moved&&Math.hypot(e.clientX-labPointer.x,e.clientY-labPointer.y)<=4;labPointer=null;$('#labCandidateMarker').classList.remove('dragging');finishColorInteraction(e,isClick)};$('#labCanvas').onpointercancel=e=>{if(e.pointerId===labPointer?.id){labPointer=null;$('#labCandidateMarker').classList.remove('dragging');cancelColorInteraction()}};
    let wheelPointer=null;const previewWheel=e=>{const hsl=hslFromWheel(e),rgb=hslToRgb(hsl);wheelCursor=hsl;setCandidate(rgbToHex(rgb.r,rgb.g,rgb.b),'wheel')};$('#wheelCanvas').onpointerdown=e=>{if(e.button!==0)return;wheelPointer={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};colorDragPreview=!!editingId;e.currentTarget.setPointerCapture(e.pointerId);$('#wheelCandidateMarker').classList.add('dragging');previewWheel(e)};$('#wheelCanvas').onpointermove=e=>{if(e.pointerId!==wheelPointer?.id)return;if(Math.hypot(e.clientX-wheelPointer.x,e.clientY-wheelPointer.y)>4)wheelPointer.moved=true;previewWheel(e)};$('#wheelCanvas').onpointerup=e=>{if(e.pointerId!==wheelPointer?.id)return;previewWheel(e);const isClick=!wheelPointer.moved&&Math.hypot(e.clientX-wheelPointer.x,e.clientY-wheelPointer.y)<=4;wheelPointer=null;$('#wheelCandidateMarker').classList.remove('dragging');finishColorInteraction(e,isClick)};$('#wheelCanvas').onpointercancel=e=>{if(e.pointerId===wheelPointer?.id){wheelPointer=null;$('#wheelCandidateMarker').classList.remove('dragging');cancelColorInteraction()}};
    $('#importScale').oninput=e=>{if(!importState)return;leaveImportPreview();importState.multiplier=+e.target.value/100;e.target.nextElementSibling.textContent=e.target.value+'%';drawImportPreview()};$('#fitImport').onclick=fitImport;$('#toggleImportPreview').onclick=()=>{if(!importState)return;if(importState.preview){leaveImportPreview();drawImportPreview()}else refreshImportPreview()};$('#importAlgorithm').onchange=e=>{if(!importState)return;const wasPreview=importState.preview;importState.algorithm=e.target.value;importState.result=null;syncImportControls();if(wasPreview)refreshImportPreview()};[['importColorOffset','maxOffset',''],['importContrastTarget','contrastTarget',''],['importContrastStrength','contrastStrength','%'],['importRegionThreshold','regionThreshold','']].forEach(([id,key,suffix])=>{const input=$('#'+id);input.oninput=e=>{if(!importState)return;importState[key]=+e.target.value;e.target.nextElementSibling.textContent=Number(importState[key]).toFixed(importState[key]%1?1:0)+suffix;importState.result=null};input.onchange=()=>{if(importState?.preview)refreshImportPreview()}});$('#confirmImport').onclick=confirmImport;
    $('#importPreview').onpointerdown=e=>{if(!importState)return;leaveImportPreview();drawImportPreview();importState.drag={x:e.clientX,y:e.clientY,ox:importState.x,oy:importState.y};e.currentTarget.setPointerCapture(e.pointerId)};$('#importPreview').onpointermove=e=>{if(!importState?.drag)return;const r=e.currentTarget.getBoundingClientRect();importState.x=importState.drag.ox+(e.clientX-importState.drag.x)*450/r.width;importState.y=importState.drag.oy+(e.clientY-importState.drag.y)*450/r.height;drawImportPreview()};$('#importPreview').onpointerup=()=>{if(importState)importState.drag=null};$('#importPreview').onwheel=e=>{e.preventDefault();if(!importState)return;leaveImportPreview();importState.multiplier=clamp(importState.multiplier*(e.deltaY<0?1.08:.92),.1,5);$('#importScale').value=Math.round(importState.multiplier*100);$('#importScale').nextElementSibling.textContent=Math.round(importState.multiplier*100)+'%';drawImportPreview()};
    const activateToolShortcut=(tool,panel)=>{setTool(tool);openPanel(panel,true)};
    document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA'].includes(document.activeElement.tagName);if(e.key==='Alt'&&!typing){e.preventDefault();if(!altEyedropper){altEyedropper=true;updateStatus()}return}if(typing)return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();redo()}else if((e.ctrlKey||e.metaKey)&&k==='c'){e.preventDefault();copySelection()}else if((e.ctrlKey||e.metaKey)&&k==='x'){e.preventDefault();cutSelection()}else if((e.ctrlKey||e.metaKey)&&k==='v'){e.preventDefault();beginPaste()}else if(e.key==='Delete'){e.preventDefault();deleteSelectionPixels()}else if(k==='b')activateToolShortcut('pen','brushPanel');else if(k==='e')activateToolShortcut('eraser','brushPanel');else if(k==='f')activateToolShortcut('fill','fillPanel');else if(k==='m')activateToolShortcut('select','selectionPanel');else if(k==='g')$('#toggleGrid').click();else if(e.key==='Enter')placePaste();else if(e.key==='Escape')selectionAction('clear')});document.addEventListener('keyup',e=>{if(e.key==='Alt'&&altEyedropper){altEyedropper=false;updateStatus()}});window.addEventListener('blur',()=>{if(altEyedropper){altEyedropper=false;updateStatus()}});
    let resizeFrame=null;const preserveViewOnResize=()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{const r=dom.viewport.getBoundingClientRect();if(r.width>0&&r.height>0)applyTransform()})};if('ResizeObserver'in window)new ResizeObserver(preserveViewOnResize).observe(dom.viewport);else window.addEventListener('resize',preserveViewOnResize);document.addEventListener('visibilitychange',()=>{if(document.hidden)saveLocal()});
  }

  function init(){bootLog('init:start');$('#appVersion').textContent='v'+APP_VERSION;buildCanvas();bootLog('canvas:built',{pixels:dom.canvas.children.length});bindEvents();bootLog('events:bound');loadLocal();renderAll();bootLog('ui:rendered',{colors:state.palette.length});setCandidate(paletteColor(state.currentId)||DEFAULT_COLOR,'selection');requestAnimationFrame(()=>requestAnimationFrame(()=>{resetView();const r=dom.viewport.getBoundingClientRect();bootLog('init:ready',{zoom:Math.round(zoom*100),viewport:{width:Math.round(r.width),height:Math.round(r.height)}})}))}
  function showStartupError(error){console.error('Pixel Atelier failed to initialize',error);bootLog('init:failed',{name:error.name,message:error.message,stack:error.stack});const notice=document.createElement('div');notice.className='startup-error';const title=document.createElement('b'),summary=document.createElement('span'),details=document.createElement('pre');title.textContent='编辑器加载失败';summary.textContent=`${error.name}: ${error.message}`;details.textContent=bootEntries.map(entry=>`+${entry.ms}ms  ${entry.stage}${entry.details?.message?` — ${entry.details.message}`:''}`).join('\n');notice.append(title,summary,details);document.body.append(notice)}
  window.addEventListener('unhandledrejection',event=>{console.error('[Pixel Atelier] 未处理的异步错误',event.reason)});
  try{init()}catch(error){showStartupError(error)}
})();
